#!/bin/sh
# ═══════════════════════════════════════════════════════════════
# setup.sh — Coup Docker Setup
# Detects public IP/hostname and patches .env.docker before
# running docker compose.
#
# Usage:
#   chmod +x setup.sh
#   ./setup.sh             # HTTP
#   ./setup.sh --https     # HTTPS (self-signed cert)
# ═══════════════════════════════════════════════════════════════
set -e

USE_HTTPS=false
for arg in "$@"; do
  case $arg in
    --https) USE_HTTPS=true ;;
  esac
done

ENV_FILE=".env.docker"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  🎮  Coup — Docker Setup"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# ── Detect public hostname ───────────────────────────────
echo "🔍  Detecting public hostname..."

# Try AWS EC2 IMDSv2 first (most reliable on EC2)
TOKEN=$(curl -sf --connect-timeout 2 \
  -X PUT "http://169.254.169.254/latest/api/token" \
  -H "X-aws-ec2-metadata-token-ttl-seconds: 21600" 2>/dev/null || true)

PUBLIC_HOST=""
if [ -n "$TOKEN" ]; then
  PUBLIC_HOST=$(curl -sf --connect-timeout 2 \
    -H "X-aws-ec2-metadata-token: $TOKEN" \
    "http://169.254.169.254/latest/meta-data/public-hostname" 2>/dev/null || true)
fi

# Fallback: try public IP
if [ -z "$PUBLIC_HOST" ]; then
  PUBLIC_HOST=$(curl -sf --connect-timeout 3 ifconfig.me 2>/dev/null || \
                curl -sf --connect-timeout 3 api.ipify.org 2>/dev/null || \
                curl -sf --connect-timeout 3 checkip.amazonaws.com 2>/dev/null || true)
fi

# Fallback: localhost
if [ -z "$PUBLIC_HOST" ]; then
  PUBLIC_HOST="localhost"
  echo "⚠️   Could not detect public IP. Using 'localhost'."
else
  echo "✅  Detected: $PUBLIC_HOST"
fi

# ── Set scheme & port ────────────────────────────────────
if [ "$USE_HTTPS" = "true" ]; then
  SCHEME="https"
  APP_PORT=80
  APP_SSL_PORT=443
  NGINX_CONFIG="./docker/nginx/default-https.conf"
  APP_URL="https://$PUBLIC_HOST"
  echo "🔒  Mode: HTTPS"
else
  SCHEME="http"
  APP_PORT=80
  APP_SSL_PORT=443
  NGINX_CONFIG="./docker/nginx/default.conf"
  APP_URL="http://$PUBLIC_HOST"
  echo "🌐  Mode: HTTP"
fi

# ── Write .env.docker ────────────────────────────────────
echo "📝  Writing $ENV_FILE..."

cat > "$ENV_FILE" <<EOF
# ─── Coup — Docker Environment ────────────────────────────
# Auto-generated by setup.sh on $(date)
# Re-run ./setup.sh to regenerate

APP_NAME=Coup
APP_ENV=production
APP_KEY=
APP_DEBUG=false
APP_URL=$APP_URL

APP_LOCALE=pt_BR
APP_FALLBACK_LOCALE=en
APP_FAKER_LOCALE=pt_BR

APP_MAINTENANCE_DRIVER=file

BCRYPT_ROUNDS=12

LOG_CHANNEL=stack
LOG_STACK=single
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=warning

# ─── Database (PostgreSQL) ─────────────────────────────
DB_CONNECTION=pgsql
DB_HOST=db
DB_PORT=5432
DB_DATABASE=coup
DB_USERNAME=coup
DB_PASSWORD=secret

# ─── Session / Cache / Queue ───────────────────────────
SESSION_DRIVER=database
SESSION_LIFETIME=120
SESSION_ENCRYPT=false
SESSION_PATH=/
SESSION_DOMAIN=null

BROADCAST_CONNECTION=reverb
FILESYSTEM_DISK=local
QUEUE_CONNECTION=sync

CACHE_STORE=database

# ─── Laravel Reverb (WebSocket server) ─────────────────
REVERB_APP_ID=597065
REVERB_APP_KEY=hdg3y2tj7k10krzct9ec
REVERB_APP_SECRET=jgr4qdlknzoqj9kfci5u
REVERB_HOST=0.0.0.0
REVERB_PORT=8080
REVERB_SCHEME=http

# ─── Vite build vars ───────────────────────────────────
# wsHost is now detected dynamically at runtime (window.location.hostname)
# Only the app KEY is needed here.
VITE_REVERB_APP_KEY=hdg3y2tj7k10krzct9ec
VITE_APP_NAME=Coup

# ─── Nginx / SSL ───────────────────────────────────────
NGINX_CONFIG=$NGINX_CONFIG
SSL_DOMAIN=$PUBLIC_HOST
APP_PORT=$APP_PORT
APP_SSL_PORT=$APP_SSL_PORT
EOF

echo "✅  $ENV_FILE written"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Public URL : $APP_URL"
echo "  WebSocket  : $(echo $SCHEME | sed 's/http/ws/')s://$PUBLIC_HOST/app/"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "▶️   Run now:"
echo "    docker compose up -d --build"
echo ""
